import requests
import random

def UpdateCountFile():
    r = {x:0 for x in range(1,46)}
    f = open("count.txt", "r")
    line = f.readline()
    lines = f.readlines()
    for l in lines: r[int(l.split('=')[0])] = int(l.split('=')[1].split('\n')[0])
    f.close()

    i = int(line.split('=')[1])
    while 1:
        i += 1
        url = 'https://www.dhlottery.co.kr/common.do?method=getLottoNumber&drwNo={}'
        url = url.format(i)
        req_result = requests.get(url)
        json_result = req_result.json()
        if json_result.get('returnValue', None) == 'fail': break
        r[json_result.get('drwtNo1', None)] += 1
        r[json_result.get('drwtNo2', None)] += 1
        r[json_result.get('drwtNo3', None)] += 1
        r[json_result.get('drwtNo4', None)] += 1
        r[json_result.get('drwtNo5', None)] += 1
        r[json_result.get('drwtNo6', None)] += 1
        r[json_result.get('bnusNo', None)] += 1
        f = open("count.txt", "w")
        f.write(f"drwNo={i}\n")
        for k,v in r.items():
            f.write(f"{k}={v}\n")
        f.close()
        print("drwNo={i} Success!")
    return i-1

def GetRecentlyNum(drwNo):
    result = ""
    while 1:
        url = 'https://www.dhlottery.co.kr/common.do?method=getLottoNumber&drwNo={}'
        url = url.format(drwNo)
        req_result = requests.get(url)
        json_result = req_result.json()
        if json_result.get('returnValue', None) == 'success':
            drwNoDate = json_result.get('drwNoDate', None)
            result = "{} {} {} {} {} {} + {}"
            result = result.format( json_result.get('drwtNo1', None),
                                    json_result.get('drwtNo2', None),
                                    json_result.get('drwtNo3', None),
                                    json_result.get('drwtNo4', None),
                                    json_result.get('drwtNo5', None),
                                    json_result.get('drwtNo6', None),
                                    json_result.get('bnusNo', None) )
            drwNo += 1
            continue
        else: break
    drwNo -= 1
    print("# Recent round information\n")
    print("drwNo :", drwNo, "\ndrwNoDate :", drwNoDate, "\nLotto Num :",result)
    return drwNo

def GetNumSortedProbabilityBase():
    try:
        f = open('count.txt', 'r')
    except FileNotFoundError:
        print("Please make a file : count.txt")
        return
    f.readline()
    lines = f.readlines()
    f.close()
    if len(lines) < 45:
        print("Please make the valid file : count.txt")
        return
    d = dict()
    for l in lines:
        d[int(l.split('=')[0])] = int(l.split('=')[1].split('\n')[0])
    sorted_d = sorted(d, key = lambda x : d[x], reverse=True)
    print("# The 'count.txt' file contains the number of winnings for all numbers from round 1 to round 'drwNo'.")
    print("# Referring to the 'count.txt' file, they are listed in order of the most winning numbers.\n")
    print("[Probability-based Sort]", end="")
    for i in range(45):
        if i % 9 == 0: print()
        print(sorted_d[i], end=" ")

def GetRandomNum():
    try:
        f = open('count.txt', 'r')
    except FileNotFoundError:
        print("Please make a file : count.txt")
        return
    f.readline()
    lines = f.readlines()
    f.close()
    if len(lines) < 45:
        print("Please make the valid file : count.txt")
        return
    w = []
    for l in lines: w.append(float(l.split("=")[1].split("\n")[0]))

    print("# The 'count.txt' file contains the number of winnings for all numbers from round 1 to round 'drwNo'.")
    print("# The probability was calculated by referring to the 'count.txt' file.")
    print("# random numbers were generated by applying each probability.\n")
    for i in range(5):
        nums = []
        while len(nums) < 6:
            num = random.choices(range(1, 46), weights = w)
            if num in nums: continue
            else: nums.extend(num)
        string = f"Set{i+1} : {nums[0]} {nums[1]} {nums[2]} {nums[3]} {nums[4]} {nums[5]}"
        print(string)

def CmdInit():
    print("\n==============================")
    print("1. Get Lotto Random Number")
    print("2. Get Lotto Recently Result")
    print("3. Get Lotto Number Sorted by Probability")
    print("4. Update the file (count.txt)")
    print("0. Exit")
    print("==============================")

def BackupFile():
    try:
        f = open('count.txt', 'r')
        lines = f.readlines()
    except FileNotFoundError:
        f = open('count.txt', 'w')
        lines = []
    f.close()

    if len(lines) < 46: return
    f = open('count_backup.txt', 'w')
    for line in lines: f.write(line)
    f.close()